# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Setup
description: Setup before building the website

inputs:
  CONFIG:
    description: 'Contents of the file `config.json` for the given environment'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    # Use setup-node's built-in functionality for caching and restoring npm dependencies
    # See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        # renovate: datasource=node-version dependency=node
        node-version: 24.14.0
        cache: 'npm'
    - name: Check npm installation
      run: npm -v
      shell: bash
    - name: Install dependencies
      run: npm ci
      shell: bash

    # Initialize the config file needed to build
    - name: Load config file
      run: echo "$CONFIG" >> config.json
      shell: bash
      env:
        CONFIG: ${{ inputs.CONFIG }}
